### ISSUE TITLE
Issue-There is no database available. Ensure that you have a database available in space 'dev' within organization ********trial” error when trying to build DB folder

### ISSUE THREAD

**Issue by mrudula1412** [SAP-samples/cloud-mdk-tutorial-samples#3]
Hello,

We are facing issue when trying “Define a Simple Data Model and OData Service with CDS” tutorial (link https://developers.sap.com/tutorials/odata-05-data-model-service.html#eee6de52-44ad-44cd-bf0d-c5869a7549c8 ). 

We are facing “There is no database available. Ensure that you have a database available in space 'dev' within organization ********trial” error when trying to build DB folder as mentioned in step 11.

Could you please help.

Regards,
Mrudula

**Comment by jitendrakansal** [comment]
@mrudula1412 this issue is not related to MDK and seems you raised it for MDK github repo. 
I request you to raise it [here](https://github.com/SAPDocuments/Tutorials/issues/new?title=Define%20a%20Simple%20Data%20Model%20and%20OData%20Service%20with%20CDS&body=Tutorial%20URL:%20https://developers.sap.com/tutorials/odata-05-data-model-service.html%0A%0APlease%20specify%20the%20step%20you%20are%20referring%20to).
Related tutorial experts will help you over there. 
I am closing this issue as of now.
