### ISSUE TITLE
No client certificate selected and other issues on mdk sdk deployment

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/cloud-mdk-tutorial-samples#5]
I'm developing an application using an IAM as identity provider. So, when my app starts, the login page launches.

In SAP MDK SDK console, I'm receiving the following issues (I'm deploying in an Android real device):

```
chromium: [ERROR:aw_contents_client_bridge.cc(257)] No client certificate selected
chromium: [INFO:CONSOLE(33)] "The key "content" is not recognized and ignored.", source: <myurl>/saml2/sso?sid=0&option=credential (33)
chromium: [INFO:CONSOLE(33)] "The key "1" is not recognized and ignored.", source: <myurl>/saml2/sso?sid=0&option=credential (33)
```

The login page doesn't show any response (error or succes). Only can't make a request to get a response.

Any way to fix it? How can I config the certificate use to run?
Enabling certificate-base authentication my device hasn't the certificate, so, the correct way to provice the access must be without this way.

**Comment by MiqueiasMaia** [comment]
An additional comment: it only happens on Android Devices with by mdk build or mobile services app.

**Comment by jitendrakansal** [comment]
@MiqueiasMaia can you share what steps you followed?

**Comment by MiqueiasMaia** [comment]
@jitendrakansal I'm following [this tutorial](https://developers.sap.com/tutorials/cp-mobile-dev-kit-build-client.html).

**Comment by jitendrakansal** [comment]
When you click on START in your MDK client, what do you see in your client? Can you share a screenshot?

**Comment by MiqueiasMaia** [comment]
I see my IAM login page. At the same time, in console display the error. When I click in "Login" nothing happens.

![image20](https://user-images.githubusercontent.com/18472559/130829408-f6b3c500-3ce0-46ee-95d6-5bd0de48d6b4.png)

**Comment by jitendrakansal** [comment]
Can you/your IdP colleagues check if there is any error in the logs that might be helpful in troubleshooting this issue?

**Comment by jitendrakansal** [comment]
Can you also run this URL in a browser (better in a private/incognito window) to check if you see the IdP login page and then if login works there?
After a successful login, you should see a responseCode in the URL and page will display HTTP status 400

e.g.
https://myorg-mypsace-com-sap-mdk-demo.cfapps.eu10.hana.ondemand.com/oauth2/api/v1/authorize?client_id=12345&response_type=code 

you can get AuthorizationEndpointUrl and ClientId from your BrandedSettings.json file OR from Mobile services.

**Comment by shalmany** [comment]
Hi @jitendrakansal ,

The issue is tha sap mdk(foundation-3.4.2.aar) inject javascript on page finished and change global variable(with name "i") of idp page.

That code below in Java class  **com.sap.cloud.mobile.foundation.authentication.WebViewActivity** cause these issue:
view.loadUrl("javascript: var allLinks = document.getElementsByTagName('a'); if (allLinks) {var i;for (i=0; i<allLinks.length; i++) {var link = allLinks[i];var target = link.getAttribute('target'); if (target && target == '_blank') {link.href = 'newtab:'+link.href;link.setAttribute('target','_self');}}}");

Can you change the code above in javascript string?
 or How can I override these behavior?

Suggestion:
- Dont use "var" in javascript code.
- Create javascript function or method to do  "allLinks" logic.

**Comment by MiqueiasMaia** [comment]
Great considerations, @shalmany. It's good to have you on our team! 🚀

**Comment by jitendrakansal** [comment]
@shalmany @MiqueiasMaia do you still see this issue?
