### ISSUE TITLE
MDK - NativeScript geolocation plugin issue (syntax error) - MAC

### ISSUE THREAD

**Issue by sequeiravistex** [SAP-samples/cloud-mdk-tutorial-samples#6]
Hello SAP,

I've been researching some materials for Demos and POCs and decided to reproduce the tutorial below:
https://developers.sap.com/tutorials/cp-mobile-dev-kit-nativescript-geolocation.html

So i've done everything mentioned on the current version of the tutorial, downloaded the latest available SDK (5.2.4, for MAC):
![image](https://user-images.githubusercontent.com/76776819/133253087-7934f2bf-44c1-4017-b241-8a78bb59d8c9.png)

After successfully building the MDK client, when running the app i got the following error:
![image](https://user-images.githubusercontent.com/76776819/133253588-b4754a82-4c66-44cd-9f27-ce66bcd39e7f.png)

It's even described as a known issues on the official SAP doc:
https://help.sap.com/doc/f53c64b93e5140918d676b927a3cd65b/Cloud/en-US/docs-en/about/releases/mdk/known-issues.html
![image](https://user-images.githubusercontent.com/76776819/133253745-b731031b-51db-4da4-9a8c-513fbdf777ee.png)

But recommending version control on the plugin:
![image](https://user-images.githubusercontent.com/76776819/133254544-bfef5d2f-63be-49bc-8e43-d33dd1c7055d.png)

So based on the current mac version (5.2.4) of the MDK Dependencies Installer, here is what the project looks like:
![image](https://user-images.githubusercontent.com/76776819/133254160-35d58231-8fef-4cbb-b7c7-a6d80f6c81c3.png)

When we got updates (as you can see above) specially for NativeScript and core...
![image](https://user-images.githubusercontent.com/76776819/133254866-cd8117c5-31fe-4383-a612-db30567b28a7.png)

So for a full "correct path" on the tutorial, for mac users, what will be the official tutorial approach here to solve this issue?

Regards.

**Comment by jitendrakansal** [comment]
@sequeiravistex 

This tutorial has been updated with latest MDK release 6.0
Due to some technical issue, the new version is not yet available on the trial download page, team is already looking into it. 

You have 2 options:

- either download the latest MDK SDK from the [service marketplace](https://launchpad.support.sap.com/#/softwarecenter/search/Mobile%2520development%2520kit) and then create a branded client
- OR follow [this](https://github.com/jitendrakansal/Tutorials/blob/cd84173204467fca458706fadf9775cd2bfbc689/tutorials/cp-mobile-dev-kit-nativescript-geolocation/cp-mobile-dev-kit-nativescript-geolocation.md ) guide (should work with 5.2.4) for the Rule and MDKProject.json

**Comment by sequeiravistex** [comment]
Hello Jitendra, sure... i've opened just to document and guide for the future updates on this tutorial...

As of now, another options is to use the "other" nativescript geolocation plugin (https://www.npmjs.com/package/nativescript-geolocation), it works on the current tutorial setup/code...

Thanks.

**Comment by jitendrakansal** [comment]
MDK SDK 6.0.x is now available on community download page.
